### ISSUE TITLE
Sources Do Not Always Load

### ISSUE THREAD

**Issue by egonspin** [mwalsh161/CommandCenter#139] opened 2020-09-14 20:40 UTC
All sources currently do not load under my ORNL_Stopgap111519 branch after applying the most recent commit;  also only the msquared source is visible in the list of GUI to select under "Sources" in the top GUI menu bar. I rolled back this commit and also cleared the preferences for all of the sources I have written and the sources still do not load up opening command center. Currently the folllowing errors are returned when selecting "Sources" from the top GUI menu bar. The error does not occur on dev. 

"Error using Base.GetClasses (line 9)
Did not find a single match for C:\Users\Administrator\projects\CommandCenter\Modules\+Sources\+msquared - found 0

Error in Base.Manager.getAvailModules (line 64)
            `[prefix,module_strs,packages] = Base.GetClasses(path,'Modules',package);  % Returns name without package name`

Error in Base.Manager.getAvailModules (line 81)
               ` Base.Manager.getAvailModules(package,h,fun_callback,fun_in_use); % Recursively call to populate`

Error in Base.Manager/getAvail (line 642)
           ` obj.getAvailModules(package,parent_menu,fun_callback,fun_in_use);`

Error in CommandCenter>menu_sources_Callback (line 418)
`handles.Managers.Sources.getAvail(hObject);`

Error in gui_mainfcn (line 95)
       ` feval(varargin{:});`

Error in CommandCenter (line 47)
   ` gui_mainfcn(gui_State, varargin{:});
`
Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)CommandCenter('menu_sources_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback."

**Comment by mwalsh161** [comment] 2020-09-14 20:51
I can't tell immediately what the issue is, but I do remember some annoyance when dealing with the `what` function and how it searches based on matlab's paths and the current directory. So one question I have is did you change your pwd when this error started? I would recommend never being inside the repository when running.

The other thing jumping out is that path name looks wrong (no slashes for those package folders). I would put a debug point [here](https://github.com/mwalsh161/CommandCenter/blob/45ee695bb4b47fdfee75eb2f65fcb85ee8fbd4a2/%2BBase/GetClasses.m#L3) and step through to see what's going wrong.

**Comment by egonspin** [comment] 2020-09-15 02:27
I did try to change the user recently to me while inside the repo. Now I see I have a conflict where the user.name and user.email inside the repo I can't change and are different from my user.name and user.email I have set globally. Maybe this is causing some conflict somehow? 

Another thing that I noticed is this same issue is arising on another branch named ornl_stopgap in which I have never seen this error and also code which I have not touched in a year roughly. So it definitely seems independent of my code but it occurs on my branches...

Should I try and remove the remote repo and try and reclone it with my user.name and user.email set the globally?

**Comment by mwalsh161** [comment] 2020-09-15 13:59
The repo's user info shouldn't be an issue. There is a global user.name/email but as you found you can easily override in any repo as well. Should be as easy as deleting those things in the git repo (not globally). `git config -e` should open the config file if you run it in the repo.

What is your MATLAB working directory when you have been running CC? Is it "C:\Users\Administrator\projects\CommandCenter"?

**Comment by egonspin** [comment] 2020-09-15 14:05
Thanks for the info. Yes you are correct the directory path is:
"C:\Users\Administrator\projects\CommandCenter".

It sounds like going through the debug steps you mentioned above is the first step then? I'll change the config file in the repo as well.

**Comment by mwalsh161** [comment] 2020-09-15 14:08
I can't think of why being in the folder would cause this issue, but my first step would be to change your working directory up a level (e.g. set it to "C:\Users\Administrator\projects"). The next thing I would do if that isn't working is put in those debug points and see what is happening (if changing folders works, I would also be curious what line of code is misbehaving still, so if you have the chance I'd still put those debug points in so you can look around).

**Comment by mwalsh161** [comment] 2020-09-15 18:23
For the record, it sounded like the solution was to make sure that MATLAB's working directory is not in the repositories folder structure. I'm going to go ahead and close this issue, but we should still try and figure out why that is.

**Closed by mwalsh161** 2020-09-15 18:23 UTC
